/*
 * This file is generated by jOOQ.
 */
package org.example.infra.jooq.tables.references


import org.example.infra.jooq.tables.Medication



/**
 * The table <code>pharmacy.medication</code>.
 */
val MEDICATION: Medication = Medication.MEDICATION
