/*
 * This file is generated by jOOQ.
 */
package org.example.infra.jooq


import kotlin.collections.List

import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        public val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    /**
     * The schema <code>pharmacy</code>.
     */
    val PHARMACY: Pharmacy get(): Pharmacy = Pharmacy.PHARMACY

    override fun getSchemas(): List<Schema> = listOf(
        Pharmacy.PHARMACY
    )
}
