/*
 * This file is generated by jOOQ.
 */
package org.example.infra.jooq


import kotlin.collections.List

import org.example.infra.jooq.tables.Medication
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Pharmacy : SchemaImpl("pharmacy", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>pharmacy</code>
         */
        val PHARMACY: Pharmacy = Pharmacy()
    }

    /**
     * The table <code>pharmacy.medication</code>.
     */
    val MEDICATION: Medication get() = Medication.MEDICATION

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Medication.MEDICATION
    )
}
