/*
 * This file is generated by jOOQ.
 */
package org.example.infra.jooq.tables


import java.util.function.Function

import org.example.infra.jooq.Pharmacy
import org.example.infra.jooq.tables.records.MedicationRecord
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Medication(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, MedicationRecord>?,
    aliased: Table<MedicationRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<MedicationRecord>(
    alias,
    Pharmacy.PHARMACY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>pharmacy.medication</code>
         */
        val MEDICATION: Medication = Medication()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MedicationRecord> = MedicationRecord::class.java

    /**
     * The column <code>pharmacy.medication.code</code>.
     */
    val CODE: TableField<MedicationRecord, String?> = createField(DSL.name("code"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>pharmacy.medication.name</code>.
     */
    val NAME: TableField<MedicationRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>pharmacy.medication.weight</code>.
     */
    val WEIGHT: TableField<MedicationRecord, Int?> = createField(DSL.name("weight"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>pharmacy.medication.image</code>.
     */
    val IMAGE: TableField<MedicationRecord, String?> = createField(DSL.name("image"), SQLDataType.VARCHAR(10), this, "")

    private constructor(alias: Name, aliased: Table<MedicationRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<MedicationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>pharmacy.medication</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pharmacy.medication</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pharmacy.medication</code> table reference
     */
    constructor(): this(DSL.name("medication"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, MedicationRecord>): this(Internal.createPathAlias(child, key), child, key, MEDICATION, null)
    override fun getSchema(): Schema? = if (aliased()) null else Pharmacy.PHARMACY
    override fun `as`(alias: String): Medication = Medication(DSL.name(alias), this)
    override fun `as`(alias: Name): Medication = Medication(alias, this)
    override fun `as`(alias: Table<*>): Medication = Medication(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Medication = Medication(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Medication = Medication(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Medication = Medication(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<String?, String?, Int?, String?> = super.fieldsRow() as Row4<String?, String?, Int?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Int?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Int?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
